-->>>>>>>>>>>>>>>>>>>>>>>>AGENCY AND FUND<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
SELECT [agency_id] AS 'Agency ID'
      ,[agency_name] AS 'Agency Name'
      --,[program_id] AS 'Service ID'
      --,[program_name] AS 'Service Name'
      --,[activity_id] AS 'Activity ID'
      --,[activity_name] AS 'Activity Name'
      ,[fund_id] AS 'Fund ID'
      ,[fund_name] AS 'Fund Name'
      --,[object_id] AS 'Object ID'
      --,[object_name] AS 'Object Name'
      --,[subobject_id] AS 'Subobject ID'
      --,[subobject_name] AS 'Subobject Name'
      ,FORMAT(SUM([prior_adopted]), 'C', 'en-us') AS 'FY21 Adopted'
      ,FORMAT(SUM([prior_actual]), 'C', 'en-us') AS 'FY21 Actual'
      ,FORMAT(SUM([prior_ytd_actual]), 'C', 'en-us') AS 'FY21 YTD Actual'
      ,FORMAT(SUM([curr_adopted]), 'C', 'en-us') AS 'FY22 Adopted'
      ,FORMAT(SUM([carry_fwd_a]), 'C', 'en-us') AS 'Carry Forward A'
      ,FORMAT(SUM([carry_fwd_b]), 'C', 'en-us') AS 'Carry Forward B'
      ,FORMAT(SUM([carry_fwd_total]), 'C', 'en-us') AS 'Carry Forward Total'
      ,FORMAT(SUM([app_adj]), 'C', 'en-us') AS 'Appropriations Adjustment'
      ,FORMAT(SUM([tot_budget]), 'C', 'en-us') AS 'Total Budget'
      ,FORMAT(SUM([jul]), 'C', 'en-us') AS 'July'
      ,FORMAT(SUM([aug]), 'C', 'en-us') AS 'August'
      ,FORMAT(SUM([sep]), 'C', 'en-us') AS 'September'
      ,FORMAT(SUM([oct]), 'C', 'en-us') AS 'October'
      ,FORMAT(SUM([nov]), 'C', 'en-us') AS 'November'
      ,FORMAT(SUM([dec]), 'C', 'en-us') AS 'December'
      ,FORMAT(SUM([jan]), 'C', 'en-us') AS 'January'
      ,FORMAT(SUM([feb]), 'C', 'en-us') AS 'February'
      ,FORMAT(SUM([mar]), 'C', 'en-us') AS 'March'
      ,FORMAT(SUM([apr]), 'C', 'en-us') AS 'April'
      ,FORMAT(SUM([may]), 'C', 'en-us') AS 'May'
      ,FORMAT(SUM([jun]), 'C', 'en-us') AS 'June'
      ,FORMAT(SUM([ytd_exp]), 'C', 'en-us') AS 'BAPS YTD Expenditures'
      ,FORMAT(SUM([tot_enc]), 'C', 'en-us') AS 'Total Encumbrance'
      ,FORMAT(SUM([cur_acc]), 'C', 'en-us') AS 'Current Accrual'
  FROM [Finance_BPFS].[planningyear23].[CURRENT_YEAR_EXPENDITURE]
  GROUP BY [agency_id], [agency_name], [fund_id], [fund_name]
  ORDER BY [agency_id], [agency_name],  [fund_id], [fund_name]

  -->>>>>>>>>>>>>>>>>>>>>>>>>SERVICE FOR PILLARS<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 
  SELECT 
		B.[Objective Name] AS 'Pillar'
      ,[program_id] AS 'Service ID'
      ,[program_name] AS 'Service Name'
      ,FORMAT(SUM([prior_adopted]), 'C', 'en-us') AS 'FY21 Adopted'
      ,FORMAT(SUM([prior_actual]), 'C', 'en-us') AS 'FY21 Actual'
      ,FORMAT(SUM([prior_ytd_actual]), 'C', 'en-us') AS 'FY21 YTD Actual'
      ,FORMAT(SUM([curr_adopted]), 'C', 'en-us') AS 'FY22 Adopted'
      ,FORMAT(SUM([carry_fwd_a]), 'C', 'en-us') AS 'Carry Forward A'
      ,FORMAT(SUM([carry_fwd_b]), 'C', 'en-us') AS 'Carry Forward B'
      ,FORMAT(SUM([carry_fwd_total]), 'C', 'en-us') AS 'Carry Forward Total'
      ,FORMAT(SUM([app_adj]), 'C', 'en-us') AS 'Appropriations Adjustment'
      ,FORMAT(SUM([tot_budget]), 'C', 'en-us') AS 'Total Budget'
      ,FORMAT(SUM([jul]), 'C', 'en-us') AS 'July'
      ,FORMAT(SUM([aug]), 'C', 'en-us') AS 'August'
      ,FORMAT(SUM([sep]), 'C', 'en-us') AS 'September'
      ,FORMAT(SUM([oct]), 'C', 'en-us') AS 'October'
      ,FORMAT(SUM([nov]), 'C', 'en-us') AS 'November'
      ,FORMAT(SUM([dec]), 'C', 'en-us') AS 'December'
      ,FORMAT(SUM([jan]), 'C', 'en-us') AS 'January'
      ,FORMAT(SUM([feb]), 'C', 'en-us') AS 'February'
      ,FORMAT(SUM([mar]), 'C', 'en-us') AS 'March'
      ,FORMAT(SUM([apr]), 'C', 'en-us') AS 'April'
      ,FORMAT(SUM([may]), 'C', 'en-us') AS 'May'
      ,FORMAT(SUM([jun]), 'C', 'en-us') AS 'June'
      ,FORMAT(SUM([ytd_exp]), 'C', 'en-us') AS 'BAPS YTD Expenditures'
      ,FORMAT(SUM([tot_enc]), 'C', 'en-us') AS 'Total Encumbrance'
      ,FORMAT(SUM([cur_acc]), 'C', 'en-us') AS 'Current Accrual'
  FROM [Finance_BPFS].[planningyear23].[CURRENT_YEAR_EXPENDITURE] A
  LEFT JOIN (SELECT [Program Name], [Program Id], [Objective Id],[Objective Name] FROM [Finance_BPFS].[planningyear23].[LINE_ITEM_REPORT_BOE]) B
  ON A.program_id = B.[Program Id]
  GROUP BY B.[Objective Name], [program_id], [program_name]
  ORDER BY B.[Objective Name], [program_id], [program_name]